### ISSUE TITLE
Bootstrap throws error 'ReferenceError: document is not defined'

### ISSUE THREAD

**Issue by pmessan** [pmessan/wishlist-app#1]
So I'm trying to import the Bootstrap JS lirary into the _app.js using [this tutorial](https://stackoverflow.com/questions/40037657/how-to-include-bootstrap-css-and-js-in-reactjs-app) and I keep getting the ff error: 
![image](https://user-images.githubusercontent.com/48386816/125179198-a3f8a180-e1db-11eb-853c-2c00b8b1aa26.png)
but get this... it only throws when the library is included when the server is started. When I include it as the server is running already, it works fine, and the collapse animations I applied work fine as well. What can I do?

**Comment by pmessan** [comment]
I thought about switching from vanilla Bootstrap to react-bootstrap cuz there's no actual Nextjs bootstrap package. @EdwinAgbakpe The link you sent earlier just installs regular bootstrap. We could customize one of [the examples they have](https://react-bootstrap.github.io/components/accordion/) under the accordion to suit our case even though they don't have the collapse animation as a stand-alone.

**Comment by pmessan** [comment]
Fixed: https://nextjs.org/docs/basic-features/script
Turns out Nextjs has a Script component. So you can add the bootstrap JS files delivered through CDNs. Piece of cake! 😂

**Comment by DR-MATTH** [comment]
this blog really explains it all [see](https://dev.to/anuraggharat/adding-bootstrap-to-nextjs-39b2), but this is the fix to 'document is not defined', in the MyApp component we need to add an useEffect hook to wait for the document to be created

> Importing JS is not easy as CSS. If we directly import JS like CSS we will run into error which would say window and document is not defined. This is because window and document are client side objects, while Next.js renders HTML on Client side as well as server side. Hence to avoid such errors we will dynamically import JS using useEffect() hook. Look at the below code.

```
function MyApp({ Component, pageProps }) {
  useEffect(() => {
    import('bootstrap')
  }, [])

  return <Component {...pageProps} />
}
```
